services:
  ai-drawing-tool:
    image: itgpt/huihua:latest
    container_name: ai-drawing-tool
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      - WECHAT_ID=p7tk19
      - MAIN_SITE_URL=https://api.wanwuhuanxin.cn
      - API_BASE_URL=https://api.wanwuhuanxin.cn
